name: 'kubectl'
author: Javier Garmon
description: Run kubectl inside Docker integrated with EKS cluster
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'mrgarmon/gh-action-docker-kubectl'
inputs:
  aws_access_key_id:
    description: Your AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: Your AWS_SECRET_ACCESS_KEY
    required: true
  aws_region:
    description: The region of the cluster
    required: true
  cluster_name:
    description: The name of the cluster you are using
    required: true
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
